### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by jwjeong-bit** [kjy00302/pylooper#3] opened 2021-05-20 10:54 UTC
Traceback (most recent call last):
File "C:\Users\정제원\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193,  in _run_module_as_main ""__main__", mod_spec)
File "C:\Users\정제원\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85,  in _run_code exec(code, run_globals)
File "C:\project\practice\pylooper\pylooper\__main__.py", line 23, in <module> looper = Looper()
File "C:\project\practice\pylooper\pylooper\aw_looper.py", line 13, in __init__ super().__init__(48000)
File "C:\project\practice\pylooper\pylooper\audioworker.py", line 16, in __init__ stream_callback=self.aw_callback
File "C:\Users\정제원\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 750,  in open stream = Stream(self, *args, **kwargs)
File "C:\Users\정제원\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 441,  in __init__ self._stream = pa.open(**arguments)
OSError: [Errno - 9996] Invalid input device ( no default output device)

**Comment by kjy00302** [comment] 2021-05-20 10:58
Duplicate of issue #2. Closing.

**Closed as completed by kjy00302** 2021-05-20 10:58 UTC
